### ISSUE TITLE
Include Sansec eComscan

### ISSUE THREAD

**Issue by sprankhub** [mage-os/infrastructure#46]
We should add https://github.com/sansecio/ecomscan-github-action to https://github.com/mage-os/mageos-magento2 (and potentially other?) repositories. Sansec is willing to give us a free license for this.

**Comment by fballiano** [comment]
@Vinai @rhoerr @aleron75 what do you think about this? It could be a nice addition especially if we can have a free license.

**Comment by rhoerr** [comment]
@fballiano I'm strongly in favor. We have a license key from them already, actually, which I can share or add in the appropriate manner. I'd just need instructions.

**Comment by fballiano** [comment]
@rhoerr I'd say create a "organization secret" at https://github.com/organizations/mage-os/settings/secrets/actions (please check the url because I don't have access to that section) and then (if you tell me the name of the secret key) I can add the workflow to one or more repo(s)

**Comment by rhoerr** [comment]
@fballiano Got it. You should be able to access it now as org secret `SANSEC_LICENSE_KEY`.

**Comment by fballiano** [comment]
@sprankhub @rhoerr now that we have it in place for https://github.com/mage-os/mageos-magento2, do we want to add it to other repos or shall we close this issue?

**Comment by sprankhub** [comment]
If we want to have it for all repositories, we can also add it via Terraform similar to how we do it with the `merge-upstream-changes.yml` workflow: https://github.com/mage-os/terraform/blob/56c902df66af86c11374375c93721d3234ca093a/main.tf#L200-L237

Maybe let's discuss in a tech meeting, if and where we want to have it besides the main repo?

**Comment by fballiano** [comment]
@sprankhub could terraform also add the workflow file to every branch in a repo?

**Comment by fballiano** [comment]
Note: I've created a Taiga task for this.

**Comment by sprankhub** [comment]
@fballiano, nope, it would create the file in the default branch. Other branches would then need to merge the default branch into them.

**Comment by fballiano** [comment]
@sprankhub since eComscan is a closed source software and we don't know exactly what it searches for, it's not clear to me if it would be beneficial to have it on every repository. However we could have a Terraform action that adds the workflow on every branch but I'd close this issue (which is solved) and open a specific one on Terraform's repo
